### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/add/operator/filter'

### ISSUE THREAD

**Issue by codekeyz** [hggeorgiev/ng2-breadcrumbs#20]
``` ERROR in ./node_modules/ng2-breadcrumbs/lib/breadcrumbs.component.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 'C:\Users\XXX\XXX\XXX\project\node_modules\ng2-breadcrumbs\lib'

Please check this out

**Comment by anita-87** [comment]
I'm having the same issue, any help please?

**Comment by x16man** [comment]
up

**Comment by itachiRedhair** [comment]
I am having the same issue... Probably you need to change the imports.

**Comment by codekeyz** [comment]
@anita-87, @x16man , @x16man, i have just submitted a PR, everything works fine now. Check out the [DEMO](https://codekeyz.github.io/ng2-breadcrumbs/)

**Comment by Gemorroj** [comment]
@hggeorgiev ping

**Comment by hggeorgiev** [comment]
Hello @Gemorroj , I'll have a look at the PR this weekend and update if everything goes okay.

**Comment by aarcangeli** [comment]
any updates? I am having the same issue

**Comment by codekeyz** [comment]
@hggeorgiev It's been a while now, PR not merged, library not updated. Please look at this asap
